solution 1-sum
js-tasks-ru/js-20210126_alexander-i-kamenev pull request #1
Opened 2021-01-16 14:09 UTC by freeman1981

Привет! вот мое решение первой задачки

2021-01-16 14:16 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ should return sum of numbers
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2021-01-28 10:55 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let res = [...arr];
`let` - мы используем в тех случаях когда нужно сделать переприсвоение значения в данную переменную. Во всех дргугих случаях следует использовать `const`

2021-01-28 10:55 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    res.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-01-28 10:56 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let res = {};
`rest` - это `const`

2021-01-28 10:56 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let entry of Object.entries(obj)) {
`entry` - это `const`

2021-01-28 10:57 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +      res[entry[0]] = entry[1];
чтобы не обращаться к значениям `entry` по индексам, следует сделать деструктурирующее присваивание внутри `for (...)`. Попробуйте поправить это.

2021-01-28 10:58 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let res = {};
аналогичные замечания как в `pick`

2021-01-28 10:59 UTC, dosandk requested changes
из критичного - следует поправить решение `sortStrings` и проверить использование `let` и `const`

2021-01-28 19:58 UTC, freeman1981 commented
поправил замечания

2021-01-29 13:05 UTC, dosandk approved these changes
good 👍

2021-02-01 10:01 UTC, dosandk commented on 01-intro/1-sum/index.js
> +  return m + n;
good 👍

2021-02-01 10:01 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
>  export function sortStrings(arr, param = 'asc') {
good 👍

2021-02-01 10:01 UTC, dosandk approved these changes
good 👍

2021-02-01 10:08 UTC, dosandk approved these changes

2021-02-02 22:02 UTC, freeman1981 commented
ну в общем продолжаю сюда 03 задачки

2021-02-04 14:55 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return undefined;
помните что мы не взаимодействуем с `undefined` напрямую, поэтому просто достаточно `return`

2021-02-04 14:55 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (const prop of path.split('.')) {
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2021-02-04 14:56 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
достаточно:
```
if (!obj) return;
```

2021-02-04 14:57 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  const set = new Set();
значения в `Set` можно добавить сразу при создании коллекции:
```
new Set([1, 2, 3])
```

2021-02-04 14:58 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return result;
также `Set` можно преобразовать обратно в массив с помощью спред синтаксиса:
```
return [...new Set(arr)];
```

2021-02-04 14:58 UTC, dosandk requested changes
необходимо внести правки в решение `createGetter`

2021-02-04 18:39 UTC, freeman1981 commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
![image](https://user-images.githubusercontent.com/7160516/106939444-50b48b80-6731-11eb-94fd-7120d20a3129.png)

может есть смысл добавить таки фигурные скобочки?

![image](https://user-images.githubusercontent.com/7160516/106939566-7a6db280-6731-11eb-8e88-1c06903944d7.png)

2021-02-04 19:14 UTC, freeman1981 commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return result;
Прикольно! не знал, что у множества есть порядок - поправил

2021-02-04 19:14 UTC, freeman1981 commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  const set = new Set();
угу - поправил

2021-02-04 19:14 UTC, freeman1981 commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
сделал без фигурных скобочек

2021-02-04 19:15 UTC, freeman1981 commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (const prop of path.split('.')) {
угу - поправил

2021-02-04 19:15 UTC, freeman1981 commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return undefined;
поправил

2021-02-05 07:01 UTC, freeman1981 commented
все поправил

2021-02-05 15:46 UTC, dosandk approved these changes

2021-02-05 15:47 UTC, merged